# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_rsurv <- function(time, prob, n_times, n_rep) {
    .Call('_rsurv_C_rsurv', PACKAGE = 'rsurv', time, prob, n_times, n_rep)
}

